# Generated by Django 6.0.6 on 2026-07-07 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='residents/')),
                ('relationship', models.CharField(choices=[('husband', 'Husband'), ('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('other', 'Other')], default='other', max_length=30)),
                ('fullname', models.CharField(max_length=180)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('passport', models.CharField(blank=True, max_length=40)),
                ('pinfl', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('workplace', models.CharField(blank=True, max_length=180)),
                ('education', models.CharField(blank=True, max_length=120)),
                ('has_violation', models.BooleanField(default=False)),
                ('violation_description', models.TextField(blank=True)),
                ('violation_date', models.DateField(blank=True, null=True)),
                ('officer_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=180)),
                ('room_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('house_number', 'street_name'), name='unique_house_per_street')],
            },
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='related_persons/')),
                ('fullname', models.CharField(max_length=180)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('organization', models.CharField(blank=True, max_length=180)),
                ('membership', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_persons', to='registry.resident')),
            ],
            options={
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField()),
                ('family_status', models.CharField(choices=[('large', 'Large Family'), ('medium', 'Medium Family'), ('small', 'Small Family')], default='small', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='registry.house')),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='registry.room'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('house', 'room_number'), name='unique_room_per_house'),
        ),
    ]
