# Generated by Django 6.0.6 on 2026-07-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol'), ('other', 'Boshqa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resident',
            name='relationship',
            field=models.CharField(choices=[('husband', 'Er'), ('wife', 'Xotin'), ('son', "O'g'il"), ('daughter', 'Qiz'), ('father', 'Ota'), ('mother', 'Ona'), ('brother', 'Aka/Uka'), ('sister', 'Opa/Singil'), ('other', 'Boshqa')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='family_status',
            field=models.CharField(choices=[('large', 'Katta oila'), ('medium', "O'rta oila"), ('small', 'Kichik oila')], default='small', max_length=20),
        ),
    ]
