# Generated by Django 6.0.6 on 2026-07-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_resident_gender_alter_resident_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='color',
            field=models.CharField(choices=[('blue', "Ko'k"), ('green', 'Yashil'), ('red', 'Qizil'), ('amber', 'Sariq'), ('slate', 'Kulrang')], default='blue', max_length=20),
        ),
    ]
