# Generated by Django 6.0.6 on 2026-07-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_house_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='apartments_per_entrance',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='house',
            name='entrance_count',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='room',
            name='entrance_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
