# Generated by Django 6.0.6 on 2026-07-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_house_apartments_per_entrance_house_entrance_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='abroad_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='resident',
            name='abroad_duration',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='resident',
            name='abroad_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='abroad_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='conviction_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='conviction_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='imprisoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='imprisoned_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='imprisonment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='living_status',
            field=models.CharField(choices=[('owner', 'Uy egasi'), ('tenant', 'Ijarada yashovchi')], default='owner', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='long_abroad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='previously_convicted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='released_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
