# Generated by Django 6.0.6 on 2026-07-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_resident_abroad_country_resident_abroad_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='imprisoned',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='imprisoned_year',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='imprisonment_note',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='released_year',
        ),
        migrations.AddField(
            model_name='resident',
            name='administrative_supervision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='administrative_supervision_end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='administrative_supervision_start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='alcohol_addiction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='alcohol_addiction_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='complaint_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='complaint_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resident',
            name='disability_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='drug_addiction_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='drug_addiction_since',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='resident',
            name='entrance_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='entrance_sos_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='has_complaints',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='hunting_weapon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='mental_health_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='needs_social_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='penal_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='penal_institution_location',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='resident',
            name='penal_institution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='preventive_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='preventive_register_article',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='resident',
            name='preventive_register_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='probation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='probation_end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='probation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='probation_start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='security_panel_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='social_assistance_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='social_conclusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='social_conclusion_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='troubled_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='troubled_family_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='weapon_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='weapon_model',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='resident',
            name='yard_camera',
            field=models.BooleanField(default=False),
        ),
    ]
