# Generated by Django 6.0.6 on 2026-07-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_remove_resident_imprisoned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='living_status',
            field=models.CharField(choices=[('owner', 'Uy egasi'), ('tenant', 'Ijarada yashovchi'), ('member', "A'zo")], default='owner', max_length=20),
        ),
    ]
