# Generated by Django 6.0.6 on 2026-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_alter_resident_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='relationship',
            field=models.CharField(choices=[('self', "O'zi"), ('son', "O'g'il"), ('daughter', 'Qiz'), ('mother', 'Ona'), ('brother', 'Akasi'), ('sister', 'Opasi'), ('friend', "Do'sti"), ('other', 'Boshqa')], default='other', max_length=30),
        ),
    ]
