# Generated by Django 6.0.6 on 2026-07-08 07:56

from django.db import migrations, models


def move_house_security_flags(apps, schema_editor):
    House = apps.get_model("registry", "House")
    Resident = apps.get_model("registry", "Resident")
    for house in House.objects.all():
        residents = Resident.objects.filter(room__house=house)
        updates = {
            "entrance_camera": residents.filter(entrance_camera=True).exists(),
            "yard_camera": residents.filter(yard_camera=True).exists(),
            "entrance_sos_button": residents.filter(entrance_sos_button=True).exists(),
        }
        if any(updates.values()):
            for field, value in updates.items():
                setattr(house, field, value)
            house.save(update_fields=list(updates.keys()))


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_resident_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='entrance_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='entrance_sos_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='yard_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(move_house_security_flags, migrations.RunPython.noop),
    ]
