# Generated by Django 6.0.6 on 2026-07-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_house_entrance_camera_house_entrance_sos_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='entrance_camera',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='entrance_sos_button',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='yard_camera',
        ),
    ]
