# Generated by Django 6.0.6 on 2026-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_remove_resident_entrance_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_studying',
            field=models.BooleanField(default=False),
        ),
    ]
