# Generated by Django 6.0.6 on 2026-07-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_resident_is_studying'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='yard_camera_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
