# Generated by Django 6.0.6 on 2026-07-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_house_yard_camera_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='conviction_article',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='resident',
            name='conviction_part',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='resident',
            name='deo_article',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='resident',
            name='deo_end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='deo_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='deo_part',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='resident',
            name='deo_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='deo_start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='has_rental_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='has_temporary_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='joint_conclusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='joint_conclusion_file',
            field=models.FileField(blank=True, null=True, upload_to='resident_documents/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='joint_conclusion_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='preventive_register_end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='preventive_register_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='preventive_register_part',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='resident',
            name='preventive_register_start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='probation_article',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='resident',
            name='probation_part',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='resident',
            name='rental_contract_file',
            field=models.FileField(blank=True, null=True, upload_to='resident_documents/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='social_conclusion_file',
            field=models.FileField(blank=True, null=True, upload_to='resident_documents/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='temporary_registration_file',
            field=models.FileField(blank=True, null=True, upload_to='resident_documents/'),
        ),
    ]
