# Generated by Django 6.0.6 on 2026-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_resident_conviction_article_resident_conviction_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='social_conclusion_provider',
            field=models.CharField(blank=True, choices=[('mfy_chair', 'MFY raisi'), ('mayor_assistant', 'Hokim yordamchisi'), ('women_activist', 'Xotin-qizlar faoli'), ('prevention_inspector', 'Profilaktika inspektori'), ('youth_leader', 'Yoshlar yetakchisi'), ('social_protection', 'Ijtimoiy himoya vakili'), ('tax_inspector', 'Soliq inspektori')], max_length=40),
        ),
    ]
