# Generated by Django 6.0.6 on 2026-07-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_resident_social_conclusion_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='entrance_camera_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='entrance_sos_button_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='social_conclusion_provider',
            field=models.CharField(blank=True, choices=[('mayor_assistant', 'Hokim yordamchisi'), ('women_activist', 'Xotin-qizlar faoli'), ('prevention_inspector', 'Profilaktika inspektori'), ('youth_leader', 'Yoshlar yetakchisi'), ('social_protection', 'Ijtimoiy himoya vakili'), ('tax_inspector', 'Soliq inspektori')], max_length=40),
        ),
    ]
