# Generated by Django 6.0.6 on 2026-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_house_entrance_camera_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='daily_rental_guest_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='has_origin_neighborhood_conclusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='origin_neighborhood_conclusion_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='apartments_per_entrance',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
