# Generated by Django 6.0.6 on 2026-07-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_resident_daily_rental_guest_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='cybersecurity_bot_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='cybersecurity_bot_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
