# Generated by Django 6.0.6 on 2026-07-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_house_cybersecurity_bot_connected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='cybersecurity_bot_connected',
        ),
        migrations.RemoveField(
            model_name='house',
            name='cybersecurity_bot_count',
        ),
        migrations.AddField(
            model_name='resident',
            name='cybersecurity_bot_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='cybersecurity_bot_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
