# Generated by Django 6.0.6 on 2026-07-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_remove_house_cybersecurity_bot_connected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='cybersecurity_bot_count',
        ),
    ]
