# Generated by Django 5.2.12 on 2026-07-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_remove_resident_cybersecurity_bot_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='relationship',
            field=models.CharField(choices=[('self', "O'zi"), ('wife', 'Xotini'), ('son', "O'g'il"), ('daughter', 'Qiz'), ('grandchild', 'Nevarasi'), ('mother', 'Ona'), ('father_in_law', 'Qayni otasi'), ('mother_in_law', 'Qayni onasi'), ('brother', 'Akasi'), ('sister', 'Opasi'), ('friend', "Do'sti"), ('other', 'Boshqa')], default='other', max_length=30),
        ),
    ]
