# Generated by Django 5.2.12 on 2026-07-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_alter_resident_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='wanted_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='wanted_person_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='relationship',
            field=models.CharField(choices=[('self', 'Uy egasi'), ('wife', 'Xotini'), ('son', "O'g'il"), ('daughter', 'Qiz'), ('grandchild', 'Nevarasi'), ('mother', 'Ona'), ('father_in_law', 'Qayni otasi'), ('mother_in_law', 'Qayni onasi'), ('brother', 'Akasi'), ('sister', 'Opasi'), ('friend', "Do'sti"), ('other', 'Boshqa')], default='other', max_length=30),
        ),
    ]
